[pytest]
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:starlette.exceptions.StarletteDeprecationWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
